### ISSUE TITLE
CosmosVbeHack + CosmosFTP

### ISSUE THREAD

**Issue by valentinbreiz** [AnErrupTion/cosmos-awesome#2]
CosmosVbeHack does not work and should therefore be removed or marked as unusable.
CosmosFTP should be added in "Libraries and utilities" (https://github.com/CosmosOS/CosmosFtp)

**Comment by AnErrupTion** [comment]
> CosmosVbeHack does not work and should therefore be removed or marked as unusable.

While it may not work, it could still serve as a useful resource. I'm not sure if I like marking repositories as unmaintained or unusable though, since well, they can still be useful.

> CosmosFTP should be added in "Libraries and utilities" (https://github.com/CosmosOS/CosmosFtp)

Added!
